version: '3.9'
services:
  go:
    container_name: go-api
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    tty: true
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./backend
        target: /go/app
    networks:
      - go_react_portfolio

  react:
    container_name: react-front
    build: 
      context: .
      dockerfile: docker/react/Dockerfile
    volumes:
      - type: bind
        source: ./front
        target: /react/app
    command: sh -c 'cd front && yarn start'
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - go_react_portfolio
  
  db:
    container_name: db
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    tty: true
    ports:
      - 3306:3306
    env_file:
      - ./.env
    volumes:
      - type: volume
        source: mysql_portfolio_volume
        target: /var/lib/mysql
      - type: bind
        source: ./db/init
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./db/conf
        target: /etc/mysql/conf.d/my.cnf
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - go_react_portfolio
      
volumes:
  mysql_portfolio_volume:
    name: mysql_portfolio_volume

networks:
  go_react_portfolio:
    external: true