version: '3.9'
services:
  go:
    container_name: go-api
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    tty: true
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./backend
        target: /go/app
    networks:
      - go_react_portfolio

  react:
    container_name: react-front
    build: 
      context: .
      dockerfile: docker/react/Dockerfile
    volumes:
      - type: bind
        source: ./front
        target: /react/app
    command: sh -c 'cd front && yarn start'
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - go_react_portfolio
  
  db:
    container_name: db
    image: postgres:13
    restart: always
    tty: true
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - postgres_portfolio_volume:/var/lib/postgresql/data
    networks:
      - go_react_portfolio
      
volumes:
  postgres_portfolio_volume:
    name: postgres_portfolio_volume

networks:
  go_react_portfolio:
    external: true