SELECT SCHEMA_NAME, DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME='kabos'
USE kabos;

CREATE TABLE IF NOT EXISTS users (
    id  int AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR (50) UNIQUE NOT NULL,
    password VARCHAR (50) NOT NULL,
    email VARCHAR (255) UNIQUE NOT NULL,
    created_on TIMESTAMP NOT NULL,
)

CREATE TABLE IF NOT EXISTS article (
    id int AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR (50) NOT NULL,
    created_on TIMESTAMP NOT NULL,
    text VARCHAR (3000) NOT NULL,
    
)